test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

#local:
#  service: Disk
#  root: <%= Rails.root.join("storage") %>

cloudinary_profile_photos:
  service: Cloudinary
  folder: <%= "skipo/#{Rails.env}/profile_photos" %>

cloudinary_workout_photos:
  service: Cloudinary
  folder: <%= "skipo/#{Rails.env}/workout_photos" %>

cloudinary:
  service: Cloudinary
  folder: <%= "skipo/#{Rails.env}" %>
